/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easytasks.Ihm;

import easytasks.Database.Exception.*;
import easytasks.Database.ActivityDAO;
import easytasks.Database.DAOFactory;
import easytasks.Metier.Activite;
import easytasks.Metier.Projet;
import easytasks.Metier.Utilisateur;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thibault, Loïs, Marion
 */
public class ActivitiesWindow extends javax.swing.JFrame {
    private int mousepX;
    private int mousepY;
    private Activite[] activitiesList;
    private Projet currentProject;
    private Utilisateur UserConnected;
    /**
     * Creates new form ActivitiesWindow
     */
    public ActivitiesWindow(Projet p, Utilisateur user) {
        this.currentProject = p;
        this.UserConnected = user;
        initComponents();
        initDBComponents();
        
        jTableActivites.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jPanelTopBar = new javax.swing.JPanel();
        jLabelLogoTop = new javax.swing.JLabel();
        jLabelExit = new javax.swing.JLabel();
        jLabelMinimize = new javax.swing.JLabel();
        jPanelMainComponent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableActivites = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanelMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 184, 162), 2));
        jPanelMain.setLayout(new java.awt.BorderLayout());

        jPanelTopBar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTopBar.setPreferredSize(new java.awt.Dimension(1024, 50));
        jPanelTopBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelTopBarMouseDragged(evt);
            }
        });
        jPanelTopBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelTopBarMousePressed(evt);
            }
        });

        jLabelLogoTop.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelLogoTop.setForeground(new java.awt.Color(0, 184, 162));
        jLabelLogoTop.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelLogoTop.setText("Activités");
        jLabelLogoTop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/closeSmallBlue.png"))); // NOI18N
        jLabelExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelExitMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelExitMouseReleased(evt);
            }
        });

        jLabelMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/minusSmallBlue.png"))); // NOI18N
        jLabelMinimize.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelTopBarLayout = new javax.swing.GroupLayout(jPanelTopBar);
        jPanelTopBar.setLayout(jPanelTopBarLayout);
        jPanelTopBarLayout.setHorizontalGroup(
            jPanelTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopBarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelLogoTop, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                .addComponent(jLabelMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabelExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanelTopBarLayout.setVerticalGroup(
            jPanelTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelMinimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopBarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelLogoTop, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabelExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelMain.add(jPanelTopBar, java.awt.BorderLayout.PAGE_START);

        jPanelMainComponent.setBackground(new java.awt.Color(214, 227, 225));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTableActivites.setBackground(new java.awt.Color(255, 255, 255));
        jTableActivites.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTableActivites.setForeground(new java.awt.Color(0, 0, 0));
        jTableActivites.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Commentaires", "Etat"
            })
            {
                @Override
                public boolean isCellEditable(int row,int column){
                    return false;
                }
            }
        );
        jTableActivites.setFocusable(false);
        jTableActivites.setGridColor(new java.awt.Color(0, 0, 0));
        jTableActivites.setRowHeight(50);
        jTableActivites.setSelectionBackground(new java.awt.Color(0, 184, 162));
        jTableActivites.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTableActivites.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableActivitesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableActivites);

        javax.swing.GroupLayout jPanelMainComponentLayout = new javax.swing.GroupLayout(jPanelMainComponent);
        jPanelMainComponent.setLayout(jPanelMainComponentLayout);
        jPanelMainComponentLayout.setHorizontalGroup(
            jPanelMainComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
        );
        jPanelMainComponentLayout.setVerticalGroup(
            jPanelMainComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );

        jPanelMain.add(jPanelMainComponent, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseEntered
        jLabelExit.setBackground(new Color(208,2,28));
        jLabelExit.setOpaque(true);
        jLabelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/closeSmallWhite.png")));
    }//GEN-LAST:event_jLabelExitMouseEntered

    private void jLabelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseExited
        jLabelExit.setBackground(new Color(0,0,0));
        jLabelExit.setOpaque(false);
        jLabelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/closeSmallBlue.png")));
    }//GEN-LAST:event_jLabelExitMouseExited

    private void jLabelExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseReleased
        this.dispose();
    }//GEN-LAST:event_jLabelExitMouseReleased

    private void jLabelMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseEntered
        jLabelMinimize.setBackground(new Color(211,211,211));
        jLabelMinimize.setOpaque(true);
        jLabelMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/minusSmallWhite.png")));
    }//GEN-LAST:event_jLabelMinimizeMouseEntered

    private void jLabelMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseExited
        jLabelMinimize.setBackground(new Color(0,0,0));
        jLabelMinimize.setOpaque(false);
        jLabelMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/minusSmallBlue.png")));
    }//GEN-LAST:event_jLabelMinimizeMouseExited

    private void jLabelMinimizeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseReleased
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseReleased

    private void jPanelTopBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTopBarMousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_jPanelTopBarMousePressed

    private void jPanelTopBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTopBarMouseDragged
        int coordX = evt.getXOnScreen();
        int coordY = evt.getYOnScreen();

        this.setLocation(coordX-this.mousepX, coordY-this.mousepY);
    }//GEN-LAST:event_jPanelTopBarMouseDragged

    private void jTableActivitesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableActivitesMouseClicked
        if (evt.getClickCount() == 2) {
            ActivityWindow ActivityWin = new ActivityWindow(activitiesList[jTableActivites.getSelectedRow()]);
        }
    }//GEN-LAST:event_jTableActivitesMouseClicked
    
    public void initDBComponents() {
        jLabelLogoTop.setText("Activités du projet : " + currentProject.getNom());
        
        ActivityDAO activityDao = DAOFactory.getActiviteDAO();
        try {
            this.activitiesList = activityDao.ReadActivities(currentProject, UserConnected);
            
            DefaultTableModel modelTableActivites = (DefaultTableModel) jTableActivites.getModel();
            for (int i = modelTableActivites.getRowCount() - 1; i >= 0; i--) {
                modelTableActivites.removeRow(i);
            }
            for (int i = 0; i < activitiesList.length; i++) {
                modelTableActivites.addRow(new Object[]{activitiesList[i].getCommentaires(), activitiesList[i].getEtat()});
                System.out.println(activitiesList[i].getNom() + " | " + activitiesList[i].getCommentaires() + " | " + activitiesList[i].getEtat());
            }
        } catch (DaoError ex) {
            System.out.println(ex.toString());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelLogoTop;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelMainComponent;
    private javax.swing.JPanel jPanelTopBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableActivites;
    // End of variables declaration//GEN-END:variables
}
