/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easytasks.Ihm;

import easytasks.Database.Exception.*;
import easytasks.Database.DAOFactory;
import easytasks.Database.ProjectDAO;
import easytasks.Metier.Projet;
import easytasks.Metier.Utilisateur;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thibault
 */
public class MainWindow extends javax.swing.JFrame {
    private int mousepX;
    private int mousepY;
    private Projet[] projectsList;
    private Utilisateur UserConnected;

    /**
     * Creates new form MainWindow
     */
    public MainWindow(Utilisateur user) {
        this.UserConnected = user;
        initComponents();
        /*jScrollPane1.getViewport().setBackground(Color.WHITE);
        jScrollPane1.getViewport().setBorder(null);
        jScrollPane1.setBorder(null);*/
        
        /*DefaultTableModel modelTableProjets = new DefaultTableModel();
        modelTableProjets.addColumn("Nom du projet");
        modelTableProjets.addColumn("Durée estimée");
        
        JTable pTableProjets=new JTable(modelTableProjets){
            public boolean isCellEditable(int row,int column){
              return false;
            }
        };
        
        
        jLabelName.setText(UserConnected.getName());
        jLabelStatut.setText(UserConnected.getStatut());
        ProjectDAO projectDao = DAOFactory.getProjectDAO();
        try {
            Projet[] projectsList = projectDao.ReadProjects(UserConnected);
            for (int i = 0; i < projectsList.length; i++) {
                modelTableProjets.addRow(new Object[]{projectsList[i].getId(), projectsList[i].getNom()});
                System.out.println(projectsList[i].getId() + " | " + projectsList[i].getNom());
            }
        } catch (DaoError ex) {
            System.out.println(ex.toString());
        }
        
        jPanelProjets.add(pTableProjets);
        jScrollPane1.setViewportView(pTableProjets);
        
        jLayeredPaneMain.add(jScrollPane1);
        jLayeredPaneMain.repaint();
        jLayeredPaneMain.revalidate();*/
        
        jPanelMenu1.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jPanelMenu2.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jPanelMenu3.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        if (this.UserConnected.getStatut() == "Client" || this.UserConnected.getStatut() == "Technicien")
            jTableProjets.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        jLabelTitle.setText("Projets");
        
        initDBComponents();
        
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    public Utilisateur getUser() {
        return this.UserConnected;
    }
    
    public void setUser(Utilisateur user) {
        this.UserConnected = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jPanelTopBar = new javax.swing.JPanel();
        jLabelLogoTop = new javax.swing.JLabel();
        jLabelExit = new javax.swing.JLabel();
        jLabelMinimize = new javax.swing.JLabel();
        jPanelAside = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jLabelStatut = new javax.swing.JLabel();
        jPanelMenuMain = new javax.swing.JPanel();
        jPanelMenu1 = new javax.swing.JPanel();
        jLabelProfilButton = new javax.swing.JLabel();
        jLabelButtonName1 = new javax.swing.JLabel();
        jPanelMenu2 = new javax.swing.JPanel();
        jLabelSettingsButton = new javax.swing.JLabel();
        jLabelButtonName2 = new javax.swing.JLabel();
        jPanelMenu3 = new javax.swing.JPanel();
        jLabelLogoutButton = new javax.swing.JLabel();
        jLabelButtonName3 = new javax.swing.JLabel();
        jPanelMainComponent = new javax.swing.JPanel();
        jPanelTitle = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelCenterMain = new javax.swing.JPanel();
        jPanelProjets = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProjets = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EasyTasks");
        setUndecorated(true);
        setSize(new java.awt.Dimension(1280, 720));

        jPanelMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanelMain.setLayout(new java.awt.BorderLayout());

        jPanelTopBar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTopBar.setPreferredSize(new java.awt.Dimension(1280, 50));
        jPanelTopBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelTopBarMouseDragged(evt);
            }
        });
        jPanelTopBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelTopBarMousePressed(evt);
            }
        });

        jLabelLogoTop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogoTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logoTextBlueSmall.png"))); // NOI18N
        jLabelLogoTop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/closeSmallBlue.png"))); // NOI18N
        jLabelExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelExitMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelExitMouseReleased(evt);
            }
        });

        jLabelMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/minusSmallBlue.png"))); // NOI18N
        jLabelMinimize.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelTopBarLayout = new javax.swing.GroupLayout(jPanelTopBar);
        jPanelTopBar.setLayout(jPanelTopBarLayout);
        jPanelTopBarLayout.setHorizontalGroup(
            jPanelTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopBarLayout.createSequentialGroup()
                .addComponent(jLabelLogoTop, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 930, Short.MAX_VALUE)
                .addComponent(jLabelMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabelExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelTopBarLayout.setVerticalGroup(
            jPanelTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogoTop, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabelExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelMinimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelMain.add(jPanelTopBar, java.awt.BorderLayout.PAGE_START);

        jPanelAside.setBackground(new java.awt.Color(0, 184, 162));
        jPanelAside.setPreferredSize(new java.awt.Dimension(250, 670));

        jLabelName.setBackground(new java.awt.Color(0, 151, 133));
        jLabelName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelName.setText("Nom");
        jLabelName.setOpaque(true);

        jLabelStatut.setBackground(new java.awt.Color(0, 151, 133));
        jLabelStatut.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelStatut.setForeground(new java.awt.Color(255, 255, 255));
        jLabelStatut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStatut.setText("Statut");
        jLabelStatut.setOpaque(true);

        jPanelMenuMain.setOpaque(false);

        jPanelMenu1.setBackground(new java.awt.Color(0, 151, 133));
        jPanelMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMenu1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMenu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMenu1MouseExited(evt);
            }
        });

        jLabelProfilButton.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProfilButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProfilButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/avatarSmallWhite.png"))); // NOI18N
        jLabelProfilButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelProfilButton.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabelProfilButton.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabelProfilButton.setPreferredSize(new java.awt.Dimension(40, 40));

        jLabelButtonName1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabelButtonName1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelButtonName1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelButtonName1.setText("Profil");
        jLabelButtonName1.setMaximumSize(new java.awt.Dimension(37, 40));
        jLabelButtonName1.setMinimumSize(new java.awt.Dimension(37, 40));
        jLabelButtonName1.setPreferredSize(new java.awt.Dimension(37, 40));

        javax.swing.GroupLayout jPanelMenu1Layout = new javax.swing.GroupLayout(jPanelMenu1);
        jPanelMenu1.setLayout(jPanelMenu1Layout);
        jPanelMenu1Layout.setHorizontalGroup(
            jPanelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelProfilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelButtonName1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelMenu1Layout.setVerticalGroup(
            jPanelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenu1Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelProfilButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelButtonName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jPanelMenu2.setBackground(new java.awt.Color(0, 151, 133));
        jPanelMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMenu2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMenu2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMenu2MouseExited(evt);
            }
        });

        jLabelSettingsButton.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSettingsButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSettingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/gearSmallWhite.png"))); // NOI18N
        jLabelSettingsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelSettingsButton.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabelSettingsButton.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabelSettingsButton.setPreferredSize(new java.awt.Dimension(40, 40));

        jLabelButtonName2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabelButtonName2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelButtonName2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelButtonName2.setText("Paramètres");
        jLabelButtonName2.setMaximumSize(new java.awt.Dimension(37, 40));
        jLabelButtonName2.setMinimumSize(new java.awt.Dimension(37, 40));
        jLabelButtonName2.setPreferredSize(new java.awt.Dimension(37, 40));

        javax.swing.GroupLayout jPanelMenu2Layout = new javax.swing.GroupLayout(jPanelMenu2);
        jPanelMenu2.setLayout(jPanelMenu2Layout);
        jPanelMenu2Layout.setHorizontalGroup(
            jPanelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenu2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelButtonName2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelMenu2Layout.setVerticalGroup(
            jPanelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenu2Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelButtonName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jPanelMenu3.setBackground(new java.awt.Color(0, 151, 133));
        jPanelMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMenu3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMenu3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMenu3MouseExited(evt);
            }
        });

        jLabelLogoutButton.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogoutButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/powerSmallWhite.png"))); // NOI18N
        jLabelLogoutButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelLogoutButton.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabelLogoutButton.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabelLogoutButton.setPreferredSize(new java.awt.Dimension(40, 40));

        jLabelButtonName3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabelButtonName3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelButtonName3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelButtonName3.setText("Déconnexion");
        jLabelButtonName3.setMaximumSize(new java.awt.Dimension(37, 40));
        jLabelButtonName3.setMinimumSize(new java.awt.Dimension(37, 40));
        jLabelButtonName3.setPreferredSize(new java.awt.Dimension(37, 40));

        javax.swing.GroupLayout jPanelMenu3Layout = new javax.swing.GroupLayout(jPanelMenu3);
        jPanelMenu3.setLayout(jPanelMenu3Layout);
        jPanelMenu3Layout.setHorizontalGroup(
            jPanelMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenu3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelButtonName3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelMenu3Layout.setVerticalGroup(
            jPanelMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenu3Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanelMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelButtonName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jPanelMenuMainLayout = new javax.swing.GroupLayout(jPanelMenuMain);
        jPanelMenuMain.setLayout(jPanelMenuMainLayout);
        jPanelMenuMainLayout.setHorizontalGroup(
            jPanelMenuMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanelMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanelMenuMainLayout.setVerticalGroup(
            jPanelMenuMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuMainLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanelMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(349, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelAsideLayout = new javax.swing.GroupLayout(jPanelAside);
        jPanelAside.setLayout(jPanelAsideLayout);
        jPanelAsideLayout.setHorizontalGroup(
            jPanelAsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelStatut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelMenuMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelAsideLayout.setVerticalGroup(
            jPanelAsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAsideLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabelStatut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jPanelMenuMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelMain.add(jPanelAside, java.awt.BorderLayout.LINE_START);

        jPanelMainComponent.setBackground(new java.awt.Color(214, 227, 225));
        jPanelMainComponent.setPreferredSize(new java.awt.Dimension(1020, 670));

        jPanelTitle.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTitle.setForeground(new java.awt.Color(0, 0, 0));
        jPanelTitle.setPreferredSize(new java.awt.Dimension(970, 61));

        jLabelTitle.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(0, 184, 162));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Titre");

        javax.swing.GroupLayout jPanelTitleLayout = new javax.swing.GroupLayout(jPanelTitle);
        jPanelTitle.setLayout(jPanelTitleLayout);
        jPanelTitleLayout.setHorizontalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTitleLayout.setVerticalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelCenterMain.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTableProjets.setBackground(new java.awt.Color(255, 255, 255));
        jTableProjets.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTableProjets.setForeground(new java.awt.Color(0, 0, 0));
        jTableProjets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom du projet", "Durée estimée"
            })
            {
                @Override
                public boolean isCellEditable(int row,int column){
                    return false;
                }
            }
        );
        jTableProjets.setFocusable(false);
        jTableProjets.setGridColor(new java.awt.Color(0, 0, 0));
        jTableProjets.setRowHeight(50);
        jTableProjets.setSelectionBackground(new java.awt.Color(0, 184, 162));
        jTableProjets.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTableProjets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProjetsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProjets);

        javax.swing.GroupLayout jPanelProjetsLayout = new javax.swing.GroupLayout(jPanelProjets);
        jPanelProjets.setLayout(jPanelProjetsLayout);
        jPanelProjetsLayout.setHorizontalGroup(
            jPanelProjetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
        );
        jPanelProjetsLayout.setVerticalGroup(
            jPanelProjetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelCenterMainLayout = new javax.swing.GroupLayout(jPanelCenterMain);
        jPanelCenterMain.setLayout(jPanelCenterMainLayout);
        jPanelCenterMainLayout.setHorizontalGroup(
            jPanelCenterMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCenterMainLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jPanelProjets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanelCenterMainLayout.setVerticalGroup(
            jPanelCenterMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenterMainLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanelProjets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelMainComponentLayout = new javax.swing.GroupLayout(jPanelMainComponent);
        jPanelMainComponent.setLayout(jPanelMainComponentLayout);
        jPanelMainComponentLayout.setHorizontalGroup(
            jPanelMainComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainComponentLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelMainComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelCenterMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelMainComponentLayout.setVerticalGroup(
            jPanelMainComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainComponentLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelCenterMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelMain.add(jPanelMainComponent, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelTopBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTopBarMousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_jPanelTopBarMousePressed

    private void jPanelTopBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTopBarMouseDragged
        int coordX = evt.getXOnScreen();
        int coordY = evt.getYOnScreen();

        this.setLocation(coordX-this.mousepX, coordY-this.mousepY);
    }//GEN-LAST:event_jPanelTopBarMouseDragged

    private void jLabelExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseReleased
        System.exit(0);
    }//GEN-LAST:event_jLabelExitMouseReleased

    private void jLabelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseExited
        jLabelExit.setBackground(new Color(0,0,0));
        jLabelExit.setOpaque(false);
        jLabelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/closeSmallBlue.png")));
    }//GEN-LAST:event_jLabelExitMouseExited

    private void jLabelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseEntered
        jLabelExit.setBackground(new Color(208,2,28));
        jLabelExit.setOpaque(true);
        jLabelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/closeSmallWhite.png")));
    }//GEN-LAST:event_jLabelExitMouseEntered

    private void jLabelMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseEntered
        jLabelMinimize.setBackground(new Color(211,211,211));
        jLabelMinimize.setOpaque(true);
        jLabelMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/minusSmallWhite.png")));
    }//GEN-LAST:event_jLabelMinimizeMouseEntered

    private void jLabelMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseExited
        jLabelMinimize.setBackground(new Color(0,0,0));
        jLabelMinimize.setOpaque(false);
        jLabelMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/minusSmallBlue.png")));
    }//GEN-LAST:event_jLabelMinimizeMouseExited

    private void jLabelMinimizeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseReleased
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseReleased

    private void jTableProjetsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProjetsMouseClicked
        if (evt.getClickCount() == 2 && (this.UserConnected.getStatut() == "Client" || this.UserConnected.getStatut() == "Technicien")) {
            ActivitiesWindow ActivitiesWin = new ActivitiesWindow(projectsList[jTableProjets.getSelectedRow()], this.UserConnected);
        }
    }//GEN-LAST:event_jTableProjetsMouseClicked

    private void jPanelMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenu1MouseClicked
        ProfileWindow ProfilWin = new ProfileWindow(UserConnected, this);
    }//GEN-LAST:event_jPanelMenu1MouseClicked

    private void jPanelMenu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenu1MouseEntered
        jPanelMenu1.setBackground(new Color(14,97,87));
    }//GEN-LAST:event_jPanelMenu1MouseEntered

    private void jPanelMenu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenu1MouseExited
        jPanelMenu1.setBackground(new Color(0,151,133));
    }//GEN-LAST:event_jPanelMenu1MouseExited

    private void jPanelMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenu2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelMenu2MouseClicked

    private void jPanelMenu2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenu2MouseEntered
        jPanelMenu2.setBackground(new Color(14,97,87));
    }//GEN-LAST:event_jPanelMenu2MouseEntered

    private void jPanelMenu2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenu2MouseExited
        jPanelMenu2.setBackground(new Color(0,151,133));
    }//GEN-LAST:event_jPanelMenu2MouseExited

    private void jPanelMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenu3MouseClicked
        Disconnect();
    }//GEN-LAST:event_jPanelMenu3MouseClicked

    private void jPanelMenu3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenu3MouseEntered
        jPanelMenu3.setBackground(new Color(14,97,87));
    }//GEN-LAST:event_jPanelMenu3MouseEntered

    private void jPanelMenu3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenu3MouseExited
        jPanelMenu3.setBackground(new Color(0,151,133));
    }//GEN-LAST:event_jPanelMenu3MouseExited

    public void Disconnect() {
        this.dispose();
        LoginWindow logWin = new LoginWindow();
    }
    
    public void initDBComponents() {
        jLabelName.setText(this.UserConnected.getName());
        jLabelStatut.setText(this.UserConnected.getStatut());
        
        ProjectDAO projectDao = DAOFactory.getProjectDAO();
        try {
            this.projectsList = projectDao.ReadProjects(UserConnected);
            
            DefaultTableModel modelTableProjets = (DefaultTableModel) jTableProjets.getModel();
            for (int i = modelTableProjets.getRowCount() - 1; i >= 0; i--) {
                modelTableProjets.removeRow(i);
            }
            for (int i = 0; i < projectsList.length; i++) {
                modelTableProjets.addRow(new Object[]{projectsList[i].getNom(), 500});
                System.out.println(projectsList[i].getId() + " | " + projectsList[i].getNom());
            }
        } catch (DaoError ex) {
            System.out.println(ex.toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelButtonName1;
    private javax.swing.JLabel jLabelButtonName2;
    private javax.swing.JLabel jLabelButtonName3;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelLogoTop;
    private javax.swing.JLabel jLabelLogoutButton;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelProfilButton;
    private javax.swing.JLabel jLabelSettingsButton;
    private javax.swing.JLabel jLabelStatut;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelAside;
    private javax.swing.JPanel jPanelCenterMain;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelMainComponent;
    private javax.swing.JPanel jPanelMenu1;
    private javax.swing.JPanel jPanelMenu2;
    private javax.swing.JPanel jPanelMenu3;
    private javax.swing.JPanel jPanelMenuMain;
    private javax.swing.JPanel jPanelProjets;
    private javax.swing.JPanel jPanelTitle;
    private javax.swing.JPanel jPanelTopBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProjets;
    // End of variables declaration//GEN-END:variables
}
