/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easytask;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author Thibault
 */
public class MainWindow extends javax.swing.JFrame {
    private int mousepX;
    private int mousepY;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jPanelTopBar = new javax.swing.JPanel();
        jLabelLogoTop = new javax.swing.JLabel();
        jLabelExit = new javax.swing.JLabel();
        jLabelMinimize = new javax.swing.JLabel();
        jPanelAside = new javax.swing.JPanel();
        jPanelMainComponent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EasyTasks");
        setUndecorated(true);
        setSize(new java.awt.Dimension(1280, 720));

        jPanelMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanelMain.setLayout(new java.awt.BorderLayout());

        jPanelTopBar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTopBar.setPreferredSize(new java.awt.Dimension(1280, 50));
        jPanelTopBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelTopBarMouseDragged(evt);
            }
        });
        jPanelTopBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelTopBarMousePressed(evt);
            }
        });

        jLabelLogoTop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogoTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logoTextBlueSmall.png"))); // NOI18N
        jLabelLogoTop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/closeSmallBlue.png"))); // NOI18N
        jLabelExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelExitMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelExitMouseReleased(evt);
            }
        });

        jLabelMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/minusSmallBlue.png"))); // NOI18N
        jLabelMinimize.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelTopBarLayout = new javax.swing.GroupLayout(jPanelTopBar);
        jPanelTopBar.setLayout(jPanelTopBarLayout);
        jPanelTopBarLayout.setHorizontalGroup(
            jPanelTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopBarLayout.createSequentialGroup()
                .addComponent(jLabelLogoTop, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 976, Short.MAX_VALUE)
                .addComponent(jLabelMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabelExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelTopBarLayout.setVerticalGroup(
            jPanelTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogoTop, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabelExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelMinimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelMain.add(jPanelTopBar, java.awt.BorderLayout.PAGE_START);

        jPanelAside.setBackground(new java.awt.Color(0, 184, 162));
        jPanelAside.setPreferredSize(new java.awt.Dimension(200, 670));

        javax.swing.GroupLayout jPanelAsideLayout = new javax.swing.GroupLayout(jPanelAside);
        jPanelAside.setLayout(jPanelAsideLayout);
        jPanelAsideLayout.setHorizontalGroup(
            jPanelAsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanelAsideLayout.setVerticalGroup(
            jPanelAsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
        );

        jPanelMain.add(jPanelAside, java.awt.BorderLayout.LINE_START);

        jPanelMainComponent.setBackground(new java.awt.Color(214, 227, 225));

        javax.swing.GroupLayout jPanelMainComponentLayout = new javax.swing.GroupLayout(jPanelMainComponent);
        jPanelMainComponent.setLayout(jPanelMainComponentLayout);
        jPanelMainComponentLayout.setHorizontalGroup(
            jPanelMainComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1076, Short.MAX_VALUE)
        );
        jPanelMainComponentLayout.setVerticalGroup(
            jPanelMainComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
        );

        jPanelMain.add(jPanelMainComponent, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelTopBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTopBarMousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_jPanelTopBarMousePressed

    private void jPanelTopBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTopBarMouseDragged
        int coordX = evt.getXOnScreen();
        int coordY = evt.getYOnScreen();

        this.setLocation(coordX-this.mousepX, coordY-this.mousepY);
    }//GEN-LAST:event_jPanelTopBarMouseDragged

    private void jLabelExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseReleased
        System.exit(0);
    }//GEN-LAST:event_jLabelExitMouseReleased

    private void jLabelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseExited
        jLabelExit.setBackground(new Color(0,0,0));
        jLabelExit.setOpaque(false);
        jLabelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/closeSmallBlue.png")));
    }//GEN-LAST:event_jLabelExitMouseExited

    private void jLabelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseEntered
        jLabelExit.setBackground(new Color(208,2,28));
        jLabelExit.setOpaque(true);
        jLabelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/closeSmallWhite.png")));
    }//GEN-LAST:event_jLabelExitMouseEntered

    private void jLabelMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseEntered
        jLabelMinimize.setBackground(new Color(211,211,211));
        jLabelMinimize.setOpaque(true);
        jLabelMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/minusSmallWhite.png")));
    }//GEN-LAST:event_jLabelMinimizeMouseEntered

    private void jLabelMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseExited
        jLabelMinimize.setBackground(new Color(0,0,0));
        jLabelMinimize.setOpaque(false);
        jLabelMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/minusSmallBlue.png")));
    }//GEN-LAST:event_jLabelMinimizeMouseExited

    private void jLabelMinimizeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseReleased
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelLogoTop;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JPanel jPanelAside;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelMainComponent;
    private javax.swing.JPanel jPanelTopBar;
    // End of variables declaration//GEN-END:variables
}
